version: "3"

services:

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/etc/prometheus:/etc/prometheus:rw

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=mmgrafana123
      - GF_LOG_LEVEL=debug
    volumes:
      - ./grafana/data/provisioning:/etc/grafana/provisioning:rw
      - ./grafana/data/dashboards:/etc/grafana/dashboards:rw
