version: "3"

services:

  splunkenterprise: 
    build: splunk 
    ports:
            - "8000:8000"
            - "9997:9997"
            - "8088:8088"
            - "1514:1514"
    environment: 
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_ENABLE_LISTEN=9997 
      - SPLUNK_ADD="tcp 1514" 
      - SPLUNK_PASSWORD=F5zmWlv48nvY
    volumes:
      - ./volumes/splunk/stu:/opt/splunk/stu/
      - ./volumes/splunk/var:/opt/splunk/var/
      - ./volumes/splunk/etc:/opt/splunk/etc/
  db:
    build: db
    ports:
            - "5432:5432"
    read_only: true
    restart: unless-stopped
    volumes:
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=MmPassWd
      - POSTGRES_DB=mattermost
    # uncomment the following to enable backup
    #  - AWS_ACCESS_KEY_ID=XXXX
    #  - AWS_SECRET_ACCESS_KEY=XXXX
    #  - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
    #  - AWS_REGION=us-east-1

  app:
    build: app
      # change `build:app` to `build:` and uncomment following lines for team edition or change UID/GID
      # context: app
      # args:
      #   - edition=team
      #   - PUID=1000
      #   - PGID=1000
    restart: unless-stopped
    hostname: mattermost
    depends_on: 
      - splunkenterprise
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      - ./volumes/app/mattermost/plugins:/mattermost/plugins:rw
      - ./volumes/app/mattermost/client-plugins:/mattermost/client/plugins:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      # set same as db credentials and dbname
      - MM_USERNAME=mmuser
      - MM_PASSWORD=MmPassWd
      - MM_DBNAME=mattermost

      # use the credentials you've set above, in the format:
      # MM_SQLSETTINGS_DATASOURCE=postgres://${MM_USERNAME}:${MM_PASSWORD}@db:5432/${MM_DBNAME}?sslmode=disable&connect_timeout=10
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:MmPassWd@db:5432/mattermost?sslmode=disable&connect_timeout=10

      # in case your config is not in default location
      #- MM_CONFIG=/mattermost/config/config.json
    logging:
      driver: splunk
      options:
        splunk-url: "https://localhost:8088"
        splunk-token: "78b3adda-9f02-47d1-bad2-04dc19a429a4"
        splunk-insecureskipverify: "true"
        splunk-format: "json"

#  web:
#    build: web
#    ports:
#      - "80:80"
#      - "443:443"
#    read_only: true
#    restart: unless-stopped
#    volumes:
#      # This directory must have cert files if you want to enable SSL
#      - ./volumes/web/cert:/cert:ro
#      - /etc/localtime:/etc/localtime:ro
    # Uncomment for SSL
    # environment:
    #  - MATTERMOST_ENABLE_SSL=true
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8067:8067"
    volumes:
      - ./nginx/data/nginx:/etc/nginx/conf.d
      - ./volumes/nginx/data/certbot/conf:/etc/letsencrypt
      - ./volumes/nginx/data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./volumes/nginx/data/certbot/conf:/etc/letsencrypt
      - ./volumes/nginx/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/etc/prometheus:/etc/prometheus:rw

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=mmgrafana123
      - GF_LOG_LEVEL=debug
    volumes:
      - ./grafana/data/provisioning:/etc/grafana/provisioning:rw
      - ./grafana/data/dashboards:/etc/grafana/dashboards:rw
  simplesaml:
    image: kristophjunge/test-saml-idp
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - SIMPLESAMLPHP_SP_ENTITY_ID=sd-saml
      - SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE=https://mattermost.stuartdoherty.com/login/sso/saml
